[extensions] 1\n hftg refactoror
lastmile-ai/aiconfig pull request #213
Opened 2023-11-15 17:11 UTC by LastMileNewGrad

[extensions] 1\n hftg refactoror

RFC:
- modelparser class name
- - `HuggingFaceTextGenerationModelParser`
- model.id() ->
- - HuggingFaceTextGenerationModelParser

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/lastmile-ai/aiconfig/pull/213).
* #212
* #210
* __->__ #213

2023-11-20 23:05 UTC, rholinshead requested changes
Mainly requesting changes so we don't re-introduce `Extensions` folder instead of just updating the files in `extensions` folder.

But some comments on the ts implementation -- I think you can just copy/paste the current core hf.ts parser here and it will have them all resolved

2023-11-20 23:05 UTC, rholinshead commented on Extensions/HuggingFace/typescript/hf.ts
> +      return output;
Need to add outputs to prompt

2023-11-20 23:05 UTC, rholinshead commented on Extensions/HuggingFace/python/src/aiconfig_extension_huggingface_textgeneration/__init__.py
Hmm, this is adding back the `Extensions` folder -- can you just add this stuff to `extensions` instead?

2023-11-20 23:07 UTC, LastMileNewGrad commented on Extensions/HuggingFace/python/src/aiconfig_extension_huggingface_textgeneration/__init__.py
I'm not sure what happened here since I remember deleting the `Extensions` Folder.  I will remake this diff stack to to make it explicit and easy to understand.

2023-11-20 23:09 UTC, rholinshead commented on Extensions/HuggingFace/python/src/aiconfig_extension_huggingface_textgeneration/__init__.py
Git (or maybe it's an OS thing) struggles with moves/renames that change only in casing; for move, normally `sl mv` will work but for this one in particular I had to use a temp folder first (https://github.com/lastmile-ai/aiconfig/pull/199)

2023-11-30 00:11 UTC, closed without merging

2023-11-30 00:11 UTC, rossdanlm commented
Will follow up later, closing for now