align deserialize() to library design
lastmile-ai/aiconfig pull request #352
Opened 2023-11-29 14:45 UTC by Ankush-lastmile

align deserialize() to library design

## What

Exclude Previous Run Outputs in Prompt Resolution (Deserialize Flow)

## Why

When resolving (deserializing) a prompt, if the promptw as executed before, the output from the previous execution is currently included in the deserialized state. While this was the expected behbaiour in the past, it has become apparent that including previous outputs is counterintuitive and not user-friendly

2023-12-06 23:10 UTC, jonathanlastmileai requested changes
I think this makes sense high-level, but it would be helpful to see some examples / a lot more context. What's an example use case of deserialize, why did it seem before like previous outputs should be kept, and why does it now seem otherwise?

2023-12-07 17:03 UTC, Ankush-lastmile commented
This was discussed offline w/ @saqadri 

> What's an example use case of deserialize

Consider this scenario:

1. First Run

- User Prompt: What is a good condiment for a burger? Respond with just the answer.
- GPT Response: Mustard

2. Subsequent Run of the Same Prompt
- Expected Behavior: The GPT should replicate its previous answer.
- Current Behavior: The GPT adds a new response while retaining the old one.

User Prompt: What is a good condiment for a burger? Respond with just the answer.
GPT previous Response included in request: Mustard
______
GPT Response: Ketchup


The desired outcome is for the GPT to consistently return only the initial response (Mustard) for repeated prompts, rather than accumulating additional responses

2023-12-07 17:27 UTC, jonathanlastmileai commented on python/src/aiconfig/default_parsers/openai.py
> +    prompt: Prompt, aiconfig: "AIConfigRuntime", messages: List, params=None, is_last_prompt: bool = False
when should it be false?

2023-12-14 20:14 UTC, Ankush-lastmile commented
Updated instead in #491

2023-12-14 20:14 UTC, closed without merging