1/n Model Parser Interface
lastmile-ai/aiconfig pull request #469
Opened 2023-12-12 21:19 UTC by Ankush-lastmile

1/n Model Parser Interface

2023-12-13 02:16 UTC, saqadri requested changes
Some comments

2023-12-13 02:16 UTC, saqadri commented on python/src/aiconfig/model_parser.py
> +            params_list (list[dict[str, Any]]): A List of dictionaries, where each dictionary is a set of parameters that directly influence the behaviour of inference.
parameters_list

2023-12-13 02:16 UTC, saqadri commented on python/src/aiconfig/model_parser.py
> +            inference_results.append(aiconfig_deep_copy)
I think we need to persist the parameters that the prompt was run with into the aiconfig, right?

2023-12-13 02:16 UTC, saqadri commented on python/src/aiconfig/model_parser.py
> +            await self.run(prompt, aiconfig_deep_copy, options, params, **kwargs)
Why is this done serially? Shouldn't we run this in parallel across all of them?

2023-12-13 02:16 UTC, saqadri commented on python/src/aiconfig/model_parser.py
> +        for params in parameters_list:
We also need exponential back off... can come in a diff above but it's critical if run() fails.

2023-12-13 02:16 UTC, saqadri commented on python/src/aiconfig/Config.py
> +        for aiconfig in batch_results:
Same problem as other function that we have no idea which parameters were applied to get this particular aiconfig.

Alternatively you could do prompt.resolve with the parameters  and return the fully resolved prompt back.

2023-12-13 05:06 UTC, Ankush-lastmile commented
Added async execution. Although the current model parsers all use synchronous api calls. Something to keep in mind and update forward

2023-12-14 21:36 UTC, Ankush-lastmile commented
>we have no idea which parameters were applied to get this particular aiconfig.

Updated output of `batch_execute()` to be a list of Execution Results, along with the corresponding completion params.

2023-12-14 22:43 UTC, saqadri approved these changes
Looks good, just one comment, and then ship it

2023-12-14 22:43 UTC, saqadri commented on python/src/aiconfig/Config.py
> +    ) -> list[Tuple["ExecuteResult", JSONObject | Any]]:
Just return the corresponding params for that run in the Tuple as well.
So Tuple["ExecuteResult", JSONObject | Any, Dict]

2023-12-14 23:28 UTC, Ankush-lastmile commented
> So Tuple["ExecuteResult", JSONObject | Any, Dict]

Updated to Tuple["ExecuteResult", JSONObject | Any, Dict]

looks like some formatting changes made it into the commit .

2023-12-15 00:22 UTC, saqadri approved these changes
Ship it!

2023-12-15 00:23 UTC, saqadri approved these changes
Ship it!

2023-12-15 00:24 UTC, saqadri approved these changes
Ship it!

2023-12-15 00:48 UTC, saqadri commented
lol no idea why it pasted my comment 3 times

2023-12-15 00:48 UTC, merged