[docs] updated getting started
lastmile-ai/aiconfig pull request #516
Opened 2023-12-18 04:51 UTC by tanya-rai

[docs] updated getting started

Cleaned up the getting started as part of docathon - note we will need to do this again when we launch local editor.

2023-12-18 16:25 UTC, saqadri requested changes
Was the typescript code updates tested? Going to pull this branch and make some suggested updates directly

2023-12-18 22:47 UTC, tanya-rai commented
There shouldn't be changes to the typescript code - sg on making the suggested updates directly!

2024-01-11 07:09 UTC, rossdanlm commented on aiconfig-docs/docs/getting-started.md
> +- Local editor to iterate on your AIConfigs
I thought we'd want to update README to include this?

2024-01-11 07:13 UTC, rossdanlm commented on aiconfig-docs/docs/getting-started.md
> +- Multi-modal ModelParsers: GPT4-V support, Whisper, HuggingFace image generation
We already have this! Here are some examples:

- text-to-speech: https://github.com/lastmile-ai/aiconfig/pull/793
- text-to-image (both hugging face and dall-e): https://github.com/lastmile-ai/aiconfig/pull/288, https://github.com/lastmile-ai/aiconfig/pull/460 
- image-to-text: https://github.com/lastmile-ai/aiconfig/pull/821, 
- automatic speech recognition (audio-to-text): https://github.com/lastmile-ai/aiconfig/pull/780

2024-01-11 07:13 UTC, rossdanlm approved these changes
lgtm, just confused that we don't want to advertise our local editor more?

2024-01-11 07:22 UTC, closed without merging